language: c
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
sudo: false
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-MacOSX-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - conda config --add channels https://conda.anaconda.org/biobuilds
install:
  - conda create --yes -n env_name python=3.5 numpy scipy zlib autoconf-update
  - source activate env_name
  - pip install scikit-bio==0.5.0
script:
  # configure and test without zlib
  - bash ./autogen.sh
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./configure --without-zlib LDFLAGS='-L/usr/lib64'; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./configure --without-zlib; fi
  - make
  - export PATH="$PWD:$PATH"; cd tests
  - python ./test_sortmerna.py; fi
  # configure and test with zlib
  - cd ../; make clean
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./configure --with-zlib LDFLAGS='-L/usr/lib64'; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./configure --with-zlib; fi
  - make
  - cd ./tests
  - python ./test_sortmerna.py
  - python ./test_sortmerna_zlib.py
