name: build on Linux

on:
  workflow_dispatch:

concurrency: 
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read
    
jobs:
  build-linux:
    name: build on Linux
    runs-on: ubuntu-latest

    steps:
    - name: git checkout
      uses: actions/checkout@v4

    - name: install gcc-11
      run: |
        sudo apt update
        sudo apt install -y gcc-11 g++-11

    - name: set gcc-11 as default
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100

    - name: verify gcc
      run: gcc --version

    - name: build
      run: |
        wget "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
        bash Miniforge3-$(uname)-$(uname -m).sh -b
        eval "$(conda shell.bash activate)"
        conda install -c conda-forge -y pyyaml jinja2 requests ninja cmake
        python setup.py -n all
        echo "=== listing dist/ ==="
        ls -l ./dist

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        retention-days: 3
        path: |
          dist/sortmerna*Linux.deb
          dist/sortmerna*Linux.sh
          dist/sortmerna*Linux.tar.gz
    
